version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    expose:
      - 8000
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379
